### ISSUE TITLE
Port to python 3 since python 2 support is soon dropped

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler-utils#1]
As discussed with @qstokkink in Tribler/tribler#5029, the python 2 support is dropped in January 1st, 2020 (two days at the time of writing), therefor imo (edit: and theirs "As Python 2 support will formally be dropped in two days (!), I think it is safe to port it fully to Python 3") it is safe to port the repo (currently a relatively simple matter) to python 3.

**Comment by devos50** [comment]
Hmm, there's not really much in this repository hehe. You want to take on the task to port the existing script, plus the ones linked in the Tribler issue to Python 3?

**Comment by Solomon1732** [comment]
Sure, why not, lol. The bash script stay as bash, right? This is only about the python scripts?

**Comment by devos50** [comment]
Yeah this should only apply to Python scripts, unless some bash script is explicitly using the Python 2 interpreter 👍

**Comment by Solomon1732** [comment]
Where's the location of the scripts?
Edit: Are all the scripts in the gist in Tribler/tribler#5029, or are there more elsewhere?

**Comment by devos50** [comment]
The script for our [spelling checker PR job](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_spelling_check/) is [here](https://gist.github.com/0b6f7aed57f698f87df4dd77feb18e9f.git). The script [that checks if the PR adds new imports](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_new_imports_check/), is [here](https://gist.github.com/0b1119bc458931d79b0402f80cf20749.git).

It would be nice if these scripts can be moved to our utils repository, and be converted to Python 3 👍

**Comment by Solomon1732** [comment]
Sorry about that. Will get on it.
